---

  - name: Restart Apache
    service: name=apache2 state=restarted
    when: ansible_os_family == "Debian" or ansible_distribution == "Ubuntu"

  - name: Restart Apache
    service: name=httpd state=restarted
    when: ansible_os_family == "CentOS" or ansible_distribution == "RedHat"
