---
- hosts: webservers
  sudo: yes
  vars: 
    http_port: 80
    doc_dir: /ansible/
    doc_root: /var/www/html/ansible
    max_clients: 5
  vars_prompt:
    - name: username
      prompt: What is your name?

  tasks:
  - name: Ensure that Apache is installed
    apt: name=apache2 state=present
    when: ansible_os_family == "Debian" or ansible_distribuition == "Ubuntu"

  - name: ENsure that Apache is installed
    yum : name=httpd state=present
    when: ansible_os_family == "CentOS" or ansible_distribution == "RedHat"

  - name: Start Apache Services
    service: name=apache2 enabled=yes state=started

 # - name: Deploy configuration file
  #  template: src=httpd.j2 dest=/etc/apache2/conf/apache2.conf
#    notify:
#       - Restart Apache

  - name: Check if directory exists
    file: path=/var/www/html/ansible state=directory

  - name: Copy Site Files
    template: src=templates/index.j2 dest={{doc_root}}/index.html
    notify: 
       - Restart Apache
  handlers:
     - name: Restart Apache
       service: name=apache2 state=restarted

- hosts: dbservers
  sudo: yes

  tasks: 
  - name: Ensure MySQL is installed
    apt: name=mysql-server state=present
    when: ansible_os_family == "Debian" or ansible_distribution == "Ubuntu"

  - name: Ensure MySQL is installed 
    yum : name=mysql-server state=present
    when: ansible_os_family == "CentOS" or ansible_distribution == "RedHat"

  - name: Start MySQL
    service: name=mysqld state=started

  - name: Start MySQL
    service: name=mysql state=started

- hosts: webservers:dbservers
  sudo: yes

  tasks:
  - name: Stop IPTABLES/UFW NOW !!!
    service: name=ufw state=stopped
  
  - name: Stop IPTABLES NOW !!!
    service: name=iptables state=stopped
