---

  - name: Ensure that Apache is installed 
    apt: name=apache2 state=present
    when: ansible_os_family == "Debian" or ansible_distribution == "Ubuntu"

  - name: Start Apache Services
    service: name=apache2 enabled=yes state=started
    when: ansible_os_family == "Debian" or ansible_distribution == "Ubuntu"

  - name: Ensure That Apache is installed
    yum: name=httpd state=present
    when: ansible_os_family == "RedHat" or ansible_distribution == "CentOS"

  - name : Start Apache Services
    service: name=httpd enabled=yes state=started
    when: ansible_os_family == "RedHat" or ansible_distribution == "CentOS"

  - name: Deploy configuration files
    template: src=index.j2 dest={{doc_root}}/index.html
